apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  labels: 
    component: backstage-hello-world
  annotations:
#   github.com/project-slug: invinciblejai/nationalparks-py
#   backstage.io/kubernetes-namespace: jai-test
    backstage.io/kubernetes-id: backstage
#   backstage.io/kubernetes-label-selector: 'app-bs=my-app'
    janus-idp.io/tekton-enabled : 'true'
spec:
  type: service
  lifecycle: unknown
  owner: temp-team-b
