apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  labels: 
    component: backstage-hello-world
  annotations:
    backstage.io/kubernetes-id: backstage
    backstage.io/kubernetes-namespace: jai-test
spec:
  type: service
  lifecycle: unknown
  owner: temp-team-b
