apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  labels: 
    component: backstage-hello-world
  annotations:
#   github.com/project-slug: invinciblejai/nationalparks-py
#   backstage.io/kubernetes-namespace: jai-test
    backstage.io/kubernetes-id: backstage
    tekton.dev/build-namespace: deb-test
spec:
  type: service
  lifecycle: unknown
  owner: temp-team-b
