apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  labels: 
    component: nationalparks-py
  annotations:
    backstage.io/kubernetes-id: backstage
spec:
  type: service
  lifecycle: unknown
  owner: temp-team-a
